### ISSUE TITLE
Unhandled exception - Host can't be null

### ISSUE THREAD

**Issue by madcar86** [mregni/BoardGameTracker#13]
I am attempting to install via Portainer and it deploys just find but I can't access the server on the given port. So I went into the logs and it si repeating the same error. What is going wrong?

 
`warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]

      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.

Unhandled exception. System.ArgumentException: Host can't be null

   at Npgsql.NpgsqlConnectionStringBuilder.PostProcessAndValidate()

   at Npgsql.NpgsqlConnection.SetupDataSource()

   at Npgsql.NpgsqlConnection.set_ConnectionString(String value)

   at Npgsql.NpgsqlConnection..ctor(String connectionString)

   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlRelationalConnection.CreateDbConnection()

   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()

   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlRelationalConnection.get_DbConnection()

   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlRelationalConnection.CloneWith(String connectionString)

   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists(Boolean async, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.ExistsAsync(CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)

   at Program.<Main>$(String[] args) in /App/BoardGameTracker.Host/Program.cs:line 146

   at Program.<Main>(String[] args)`

**Comment by dansenMONSEN** [comment]
Got the same problem

**Comment by dansenMONSEN** [comment]
I've used uping/boardgametracker:dev as image.
The dev tag is working.
https://hub.docker.com/layers/uping/boardgametracker/dev/images/sha256-fcb360bb8aaf233e69a9a93ab24695ddb7fd0a74d9d5339cb9ffec282780b997?context=explore

**Comment by madcar86** [comment]
Changing it dev, didn't help. It has something to do with the DB_HOST variable. For some reason, it is coming out null when running the compose. But I am no expert. It's just a guess based on error
"Unhandled exception. System.ArgumentException: Host can't be null"

Can you post your latest docker-compose with env variables?

I really want to get this running, I've been looking for exactly something like this.

**Comment by dansenMONSEN** [comment]
```services:
  boardgametracker:
    image: uping/boardgametracker:dev
    restart: unless-stopped
    volumes:
      - /opt/docker/boardgametracker/images:/app/images
      - /opt/docker/boardgametracker/data:/app/data
    ports:
      - 5444:5444
    environment:
      - DB_HOST=db
      - DB_USER=dev
      - DB_PASSWORD=xxxx
      - DB_NAME=boardgametracker
      - DB_PORT=5432
      - STATISTICS=0
    depends_on:
      - db
    networks:
      - boardgametracker-net
  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - /opt/docker/boardgametracker/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=boardgametracker
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=xxxx
    ports:
      - 5432:5432
    networks:
      - boardgametracker-net

networks:
  boardgametracker-net:```

**Comment by madcar86** [comment]
I am not sure what did it, because my compose looks just like yours. But it is working now

**Comment by mregni** [comment]
Hi, sorry I didn't see this issue sooner but thanks for wanting to test my app!

I'm also in the middle of getting this app into some kind of beta stage but I will look into your issue tomorrow when I have more time.

**Comment by aerosteon** [comment]
I get the error as above, and the app container just restarts over and over, can't get it working at all.

**Comment by aerosteon** [comment]
I also got this working using /dev, had to set the password manually in the db container though
